-- Usando o Merge para alterar os dados

SELECT * FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS ORDER BY CODIGO_DO_PRODUTO;

-- Vamos usar este update para mudar os valores da coluna PRECO_LISTA em A e B pois os valores
--Estão sendo retornardos iguais de outras alteraçoes

UPDATE SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS SET PRECO_DE_LISTA = PRECO_DE_LISTA * 1.20;
SELECT * FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS ORDER BY CODIGO_DO_PRODUTO;


-- Seleciona da Tabela A e B (CODIGO, PREÇO)
SELECT A.CODIGO	AS CODIGO_MINHA_TABELA, A.PRECO_LISTA AS PRECO_MINHA_TABELA,
B.CODIGO_DO_PRODUTO AS CODIGO_TABELA_APOIO, B.PRECO_DE_LISTA AS PRECO_TABELA_APOIO
FROM PRODUTOS A	
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO;

--Usando o Merge

MERGE INTO PRODUTOS A
USING SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO
WHEN MATCHED THEN
UPDATE SET A.PRECO_LISTA = B.PRECO_DE_LISTA;

--Merge tem a função de pegar um dado de uma tabela e tranferir para outra tabela